[project]
name = "box-and-ppe-detector-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fabricio Flores", email = "Fabricio.Flores0125@jala.university" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "opencv-python>=5.0.0.93",
    "ultralytics>=8.4.158",
]

[project.scripts]
box-and-ppe-detector-v1 = "box_and_ppe_detector_v1:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
